version: "3"
services:
  localstack:
    container_name: "localstack"
    image: localstack:0.11.0-java11
    ports:
      - "4567-4599:4567-4599"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
    privileged: true
